# Provisioning
V_CPU = 1
V_MEM = 1024
BOX_NAME = "generic/ubuntu2004"
BOX_URL = "https://app.vagrantup.com/generic/boxes/ubuntu2004/versions/4.2.8/providers/virtualbox.box"
BOX_AUTO_UPDATE = false

# Server
SERVER_HOSTNAME = "jjourdan-S"
SERVER_IP = "192.168.42.110"

Vagrant.configure("2") do |config|
	config.vm.box = BOX_NAME
	config.vm.box_url = BOX_URL
	config.vm.box_check_update = BOX_AUTO_UPDATE

	config.vm.provider "virtualbox" do |v|
		v.cpus = V_CPU
		v.memory = V_MEM
	end

	config.vm.define SERVER_HOSTNAME do |master|
		master.vm.network :private_network, ip: SERVER_IP
		master.vm.hostname = SERVER_HOSTNAME
		master.vm.provider "virtualbox" do |v|
			v.name = SERVER_HOSTNAME
		end
    master.vm.synced_folder "./app", "/vagrant/app", type: "virtualbox"
    master.vm.provision "shell", privileged: true, path: "script/app.sh", args: [SERVER_IP]
	end
end
