# Provisioning
V_CPU = 1
V_MEM = 1024
BOX_NAME = "generic/ubuntu2004"
BOX_URL = "https://app.vagrantup.com/generic/boxes/ubuntu2004/versions/4.2.8/providers/virtualbox.box"
BOX_AUTO_UPDATE = false

# Server
SERVER_HOSTNAME = "jjourdan-S"
SERVER_IP = "192.168.42.110"

# ServerWorker
WORKER_HOSTNAME = "jjourdan-SW"
WORKER_IP = "192.168.42.111"


Vagrant.configure("2") do |config|
	config.vm.box = BOX_NAME
	config.vm.box_url = BOX_URL
	config.vm.box_check_update = BOX_AUTO_UPDATE

	config.vm.provider "virtualbox" do |v|
		v.cpus = V_CPU
		v.memory = V_MEM
	end

	config.vm.define SERVER_HOSTNAME do |master|
		master.vm.network :private_network, ip: SERVER_IP
		master.vm.hostname = SERVER_HOSTNAME
		master.vm.provider "virtualbox" do |v|
			v.name = SERVER_HOSTNAME
		end
    master.vm.synced_folder "./server", "/vagrant/server", type: "virtualbox"
    master.vm.synced_folder "./shared", "/vagrant/shared", type: "virtualbox"
    master.vm.provision "shell", privileged: true, path: "script/server.sh", args: [SERVER_IP]
	end

	config.vm.define WORKER_HOSTNAME do |worker|
		worker.vm.network :private_network, ip: WORKER_IP
		worker.vm.hostname = WORKER_HOSTNAME
		worker.vm.provider "virtualbox" do |v|
			v.name = WORKER_HOSTNAME
		end
    worker.vm.synced_folder "./worker", "/vagrant/worker", type: "virtualbox"
    worker.vm.synced_folder "./shared", "/vagrant/shared", type: "virtualbox"
    worker.vm.provision "shell", privileged: true, path: "script/worker.sh", args: [SERVER_IP, WORKER_IP]
	end
end
